# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b076b22e8497028772a36350cbd41c37d7ea3ed8c123d1eeea79cc9f0737f8347a8f66fa8b2240bff99f0ebd9609c9c826116d0ee942e518b68517d8964822b

test:
  secret_key_base: a5e100ae84057c31a358f345d3510d865f611d4ccf101f64d0643060a8a44e949f5b3023bc76c11f322084bd9d9e6818db4a92b6923eeba5ad1c65a0657aad07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
